# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Rheo_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 745)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_top = QtWidgets.QFrame(self.centralwidget)
        self.frame_top.setGeometry(QtCore.QRect(520, 20, 481, 311))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.frame_bottom = QtWidgets.QFrame(self.centralwidget)
        self.frame_bottom.setGeometry(QtCore.QRect(520, 360, 481, 311))
        self.frame_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom.setObjectName("frame_bottom")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 50, 301, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_data_bar = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_data_bar.sizePolicy().hasHeightForWidth())
        self.load_data_bar.setSizePolicy(sizePolicy)
        self.load_data_bar.setText("")
        self.load_data_bar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.load_data_bar.setReadOnly(True)
        self.load_data_bar.setObjectName("load_data_bar")
        self.verticalLayout.addWidget(self.load_data_bar)
        self.pushButton_load_data = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load_data.setGeometry(QtCore.QRect(230, 100, 81, 31))
        self.pushButton_load_data.setObjectName("pushButton_load_data")
        self.replot_data_button = QtWidgets.QPushButton(self.centralwidget)
        self.replot_data_button.setGeometry(QtCore.QRect(210, 590, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.replot_data_button.setFont(font)
        self.replot_data_button.setObjectName("replot_data_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, 150, 311, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.top_box_title_text = QtWidgets.QPlainTextEdit(self.frame)
        self.top_box_title_text.setGeometry(QtCore.QRect(53, 0, 201, 31))
        self.top_box_title_text.setObjectName("top_box_title_text")
        self.top_box_x_label_text = QtWidgets.QPlainTextEdit(self.frame)
        self.top_box_x_label_text.setGeometry(QtCore.QRect(53, 60, 201, 31))
        self.top_box_x_label_text.setObjectName("top_box_x_label_text")
        self.top_box_y_label_text = QtWidgets.QPlainTextEdit(self.frame)
        self.top_box_y_label_text.setGeometry(QtCore.QRect(53, 120, 201, 31))
        self.top_box_y_label_text.setObjectName("top_box_y_label_text")
        self.bottom_box_title_text = QtWidgets.QPlainTextEdit(self.frame)
        self.bottom_box_title_text.setGeometry(QtCore.QRect(53, 200, 201, 31))
        self.bottom_box_title_text.setObjectName("bottom_box_title_text")
        self.bottom_box_y_label_text = QtWidgets.QPlainTextEdit(self.frame)
        self.bottom_box_y_label_text.setGeometry(QtCore.QRect(53, 320, 201, 31))
        self.bottom_box_y_label_text.setObjectName("bottom_box_y_label_text")
        self.bottom_box_x_label_text = QtWidgets.QPlainTextEdit(self.frame)
        self.bottom_box_x_label_text.setGeometry(QtCore.QRect(53, 260, 201, 31))
        self.bottom_box_x_label_text.setObjectName("bottom_box_x_label_text")
        self.top_plot_title = QtWidgets.QLabel(self.frame)
        self.top_plot_title.setGeometry(QtCore.QRect(120, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.top_plot_title.setFont(font)
        self.top_plot_title.setObjectName("top_plot_title")
        self.top_plot_xlabel = QtWidgets.QLabel(self.frame)
        self.top_plot_xlabel.setGeometry(QtCore.QRect(120, 90, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.top_plot_xlabel.setFont(font)
        self.top_plot_xlabel.setObjectName("top_plot_xlabel")
        self.top_plot_ylabel = QtWidgets.QLabel(self.frame)
        self.top_plot_ylabel.setGeometry(QtCore.QRect(120, 150, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.top_plot_ylabel.setFont(font)
        self.top_plot_ylabel.setObjectName("top_plot_ylabel")
        self.bottom_plot_title = QtWidgets.QLabel(self.frame)
        self.bottom_plot_title.setGeometry(QtCore.QRect(120, 230, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bottom_plot_title.setFont(font)
        self.bottom_plot_title.setObjectName("bottom_plot_title")
        self.bottom_plot_xlabel = QtWidgets.QLabel(self.frame)
        self.bottom_plot_xlabel.setGeometry(QtCore.QRect(110, 290, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bottom_plot_xlabel.setFont(font)
        self.bottom_plot_xlabel.setObjectName("bottom_plot_xlabel")
        self.bottom_plot_xlabel_2 = QtWidgets.QLabel(self.frame)
        self.bottom_plot_xlabel_2.setGeometry(QtCore.QRect(110, 350, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bottom_plot_xlabel_2.setFont(font)
        self.bottom_plot_xlabel_2.setObjectName("bottom_plot_xlabel_2")
        self.export_top_plot_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_top_plot_button.setGeometry(QtCore.QRect(110, 640, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.export_top_plot_button.setFont(font)
        self.export_top_plot_button.setObjectName("export_top_plot_button")
        self.export_bottom_plot_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_bottom_plot_button.setGeometry(QtCore.QRect(310, 640, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.export_bottom_plot_button.setFont(font)
        self.export_bottom_plot_button.setObjectName("export_bottom_plot_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_data_bar.setPlaceholderText(_translate("MainWindow", "<output filename>"))
        self.pushButton_load_data.setText(_translate("MainWindow", "Load Data"))
        self.replot_data_button.setText(_translate("MainWindow", "Replot Data"))
        self.top_plot_title.setText(_translate("MainWindow", "Top Plot Title"))
        self.top_plot_xlabel.setText(_translate("MainWindow", "Top Plot X Label"))
        self.top_plot_ylabel.setText(_translate("MainWindow", "Top Plot Y Label"))
        self.bottom_plot_title.setText(_translate("MainWindow", "Bottom Plot Title"))
        self.bottom_plot_xlabel.setText(_translate("MainWindow", "Bottom Plot X Label"))
        self.bottom_plot_xlabel_2.setText(_translate("MainWindow", "Bottom Plot X Label"))
        self.export_top_plot_button.setText(_translate("MainWindow", "Export Top Plot"))
        self.export_bottom_plot_button.setText(_translate("MainWindow", "Export Bottom Plot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
